# Generated by Django 5.2.4 on 2025-07-23 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Targa',
            fields=[
                ('numero', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Targa',
                'verbose_name_plural': 'Targhe',
            },
        ),
        migrations.CreateModel(
            name='Veicolo',
            fields=[
                ('telaio', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modello', models.CharField(max_length=50)),
                ('data_produzione', models.DateField()),
            ],
            options={
                'verbose_name': 'Veicolo',
                'verbose_name_plural': 'Veicoli',
            },
        ),
        migrations.CreateModel(
            name='Revisione',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('dataRev', models.DateField()),
                ('esito', models.CharField(blank=True, choices=[('', 'In attesa di esito'), ('Superata', 'Superata'), ('Non superata', 'Non superata')], default='', max_length=20)),
                ('targaNumero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.targa')),
            ],
            options={
                'verbose_name': 'Revisione',
                'verbose_name_plural': 'Revisioni',
            },
        ),
        migrations.AddField(
            model_name='targa',
            name='telaio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.veicolo'),
        ),
        migrations.CreateModel(
            name='Restituita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_restituzione', models.DateField()),
                ('targaNumero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.targa')),
                ('veicoloTelaio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.veicolo')),
            ],
            options={
                'verbose_name': 'Restituita',
                'verbose_name_plural': 'Restituite',
                'db_table': 'Restituita',
                'unique_together': {('targaNumero', 'veicoloTelaio')},
            },
        ),
        migrations.CreateModel(
            name='Attiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targaNumero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.targa')),
                ('veicoloTelaio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.veicolo')),
            ],
            options={
                'verbose_name': 'Attiva',
                'verbose_name_plural': 'Attive',
                'db_table': 'Attiva',
                'unique_together': {('targaNumero', 'veicoloTelaio')},
            },
        ),
    ]
