# Generated by Django 5.2.4 on 2025-07-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisione',
            name='motivazione',
            field=models.TextField(blank=True, null=True),
        ),
    ]
