# Generated by Django 5.2.4 on 2025-07-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_revisione_motivazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='targa',
            name='dataEm',
            field=models.DateField(blank=True, db_column='data_emissione', help_text='Data in cui la targa è stata rilasciata', null=True, verbose_name='Data di emissione'),
        ),
    ]
