# Generated by Django 5.2.4 on 2025-07-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_targa_dataem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targa',
            name='telaio',
        ),
    ]
